apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-training-job
  namespace: ml-training
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: pytorch-training
    spec:
      restartPolicy: Never
      containers:
        - name: training
          image: mlops-train:v1
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: training-config
              mountPath: /app/configs
            - name: data-volume
              mountPath: /app/data
            - name: checkpoint-volume
              mountPath: /app/checkpoints
      volumes:
        - name: training-config
          configMap:
            name: training-config
        - name: data-volume
          emptyDir: {}
        - name: checkpoint-volume
          emptyDir: {}
